"""Initial migration with all models

Revision ID: a38dd0c89b2f
Revises: 
Create Date: 2025-12-03 20:56:23.942038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38dd0c89b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_email'), ['email'], unique=True)

    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.create_index('idx_block_court_date', ['court_id', 'date'], unique=False)
        batch_op.create_index('idx_block_date', ['date'], unique=False)

    op.create_table('favourite',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('member_id != favourite_id', name='check_not_self_favourite'),
    sa.ForeignKeyConstraint(['favourite_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'favourite_id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('idx_notification_recipient', ['recipient_id'], unique=False)
        batch_op.create_index('idx_notification_timestamp', ['timestamp'], unique=False)

    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('booked_for_id', sa.Integer(), nullable=False),
    sa.Column('booked_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booked_by_id'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booked_for_id'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'date', 'start_time', name='unique_booking')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index('idx_reservation_booked_by', ['booked_by_id'], unique=False)
        batch_op.create_index('idx_reservation_booked_for', ['booked_for_id'], unique=False)
        batch_op.create_index('idx_reservation_date', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index('idx_reservation_date')
        batch_op.drop_index('idx_reservation_booked_for')
        batch_op.drop_index('idx_reservation_booked_by')

    op.drop_table('reservation')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('idx_notification_timestamp')
        batch_op.drop_index('idx_notification_recipient')

    op.drop_table('notification')
    op.drop_table('favourite')
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_index('idx_block_date')
        batch_op.drop_index('idx_block_court_date')

    op.drop_table('block')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_email'))

    op.drop_table('member')
    op.drop_table('court')
    # ### end Alembic commands ###
